baseURL = "https://1090mhz.github.io/imgui_manual_online/"
languageCode = "en-us"
title = "ImGui Manual"
theme = "hugograyscale"

googleAnalytics = "UA-130907315-2"
disableKinds = ["taxonomy", "taxonomyTerm"]

[Author]
    name = "Pascal Thomet"
    email = "pthomet@gmail.com"

[params]
    # Provide some metadata for search and indexing services
    description = "An interactive online manual for ImGui"

#[Social]
#    twitter = "stream_running"
